package com.path.dbmaps.vo;

import com.path.vo.omni.common.base.OmniBaseVO;
import java.math.BigDecimal;

public class OC_APP_CHNLVOKey extends OmniBaseVO {
    /**
     * This field corresponds to the database column OC_APP_CHNL.APP_CHNL_ID
     */
    private BigDecimal APP_CHNL_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.APP_CHNL_ID
     *
     * @return the value of OC_APP_CHNL.APP_CHNL_ID
     */
    public BigDecimal getAPP_CHNL_ID() {
        return APP_CHNL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.APP_CHNL_ID
     *
     * @param APP_CHNL_ID the value for OC_APP_CHNL.APP_CHNL_ID
     */
    public void setAPP_CHNL_ID(BigDecimal APP_CHNL_ID) {
        this.APP_CHNL_ID = APP_CHNL_ID;
    }
}