package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class OC_APP_CHNLVO extends OC_APP_CHNLVOKey {
    /**
     * This field corresponds to the database column OC_APP_CHNL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.APP_ID
     */
    private BigDecimal APP_ID;

    /**
     * This field corresponds to the database column OC_APP_CHNL.CHNL_ID
     */
    private BigDecimal CHNL_ID;

    /**
     * This field corresponds to the database column OC_APP_CHNL.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column OC_APP_CHNL.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column OC_APP_CHNL.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column OC_APP_CHNL.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column OC_APP_CHNL.REF_CODE
     */
    private BigDecimal REF_CODE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.SUSPENDED_REASON
     */
    private String SUSPENDED_REASON;

    /**
     * This field corresponds to the database column OC_APP_CHNL.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column OC_APP_CHNL.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column OC_APP_CHNL.REJECTED_DATE
     */
    private Date REJECTED_DATE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.SUSPENDED_BY
     */
    private String SUSPENDED_BY;

    /**
     * This field corresponds to the database column OC_APP_CHNL.SUSPENDED_DATE
     */
    private Date SUSPENDED_DATE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.REACTIVATED_BY
     */
    private String REACTIVATED_BY;

    /**
     * This field corresponds to the database column OC_APP_CHNL.REACTIVATED_DATE
     */
    private Date REACTIVATED_DATE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.SUSPENDED_FROM_DATE
     */
    private Date SUSPENDED_FROM_DATE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.SUSPENDED_TO_DATE
     */
    private Date SUSPENDED_TO_DATE;

    /**
     * This field corresponds to the database column OC_APP_CHNL.SHOW_SUSPEND_REASON_LOGIN_YN
     */
    private String SHOW_SUSPEND_REASON_LOGIN_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.COMP_CODE
     *
     * @return the value of OC_APP_CHNL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.COMP_CODE
     *
     * @param COMP_CODE the value for OC_APP_CHNL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.APP_ID
     *
     * @return the value of OC_APP_CHNL.APP_ID
     */
    public BigDecimal getAPP_ID() {
        return APP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.APP_ID
     *
     * @param APP_ID the value for OC_APP_CHNL.APP_ID
     */
    public void setAPP_ID(BigDecimal APP_ID) {
        this.APP_ID = APP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.CHNL_ID
     *
     * @return the value of OC_APP_CHNL.CHNL_ID
     */
    public BigDecimal getCHNL_ID() {
        return CHNL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.CHNL_ID
     *
     * @param CHNL_ID the value for OC_APP_CHNL.CHNL_ID
     */
    public void setCHNL_ID(BigDecimal CHNL_ID) {
        this.CHNL_ID = CHNL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.CREATED_BY
     *
     * @return the value of OC_APP_CHNL.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.CREATED_BY
     *
     * @param CREATED_BY the value for OC_APP_CHNL.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.CREATED_DATE
     *
     * @return the value of OC_APP_CHNL.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.CREATED_DATE
     *
     * @param CREATED_DATE the value for OC_APP_CHNL.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.MODIFIED_BY
     *
     * @return the value of OC_APP_CHNL.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for OC_APP_CHNL.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.DATE_UPDATED
     *
     * @return the value of OC_APP_CHNL.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for OC_APP_CHNL.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.STATUS
     *
     * @return the value of OC_APP_CHNL.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.STATUS
     *
     * @param STATUS the value for OC_APP_CHNL.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.REF_CODE
     *
     * @return the value of OC_APP_CHNL.REF_CODE
     */
    public BigDecimal getREF_CODE() {
        return REF_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.REF_CODE
     *
     * @param REF_CODE the value for OC_APP_CHNL.REF_CODE
     */
    public void setREF_CODE(BigDecimal REF_CODE) {
        this.REF_CODE = REF_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.MODIFIED_DATE
     *
     * @return the value of OC_APP_CHNL.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for OC_APP_CHNL.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.SUSPENDED_REASON
     *
     * @return the value of OC_APP_CHNL.SUSPENDED_REASON
     */
    public String getSUSPENDED_REASON() {
        return SUSPENDED_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.SUSPENDED_REASON
     *
     * @param SUSPENDED_REASON the value for OC_APP_CHNL.SUSPENDED_REASON
     */
    public void setSUSPENDED_REASON(String SUSPENDED_REASON) {
        this.SUSPENDED_REASON = SUSPENDED_REASON == null ? null : SUSPENDED_REASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.APPROVED_BY
     *
     * @return the value of OC_APP_CHNL.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.APPROVED_BY
     *
     * @param APPROVED_BY the value for OC_APP_CHNL.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.APPROVED_DATE
     *
     * @return the value of OC_APP_CHNL.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for OC_APP_CHNL.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.REJECTED_BY
     *
     * @return the value of OC_APP_CHNL.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.REJECTED_BY
     *
     * @param REJECTED_BY the value for OC_APP_CHNL.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.REJECTED_DATE
     *
     * @return the value of OC_APP_CHNL.REJECTED_DATE
     */
    public Date getREJECTED_DATE() {
        return REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.REJECTED_DATE
     *
     * @param REJECTED_DATE the value for OC_APP_CHNL.REJECTED_DATE
     */
    public void setREJECTED_DATE(Date REJECTED_DATE) {
        this.REJECTED_DATE = REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.SUSPENDED_BY
     *
     * @return the value of OC_APP_CHNL.SUSPENDED_BY
     */
    public String getSUSPENDED_BY() {
        return SUSPENDED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.SUSPENDED_BY
     *
     * @param SUSPENDED_BY the value for OC_APP_CHNL.SUSPENDED_BY
     */
    public void setSUSPENDED_BY(String SUSPENDED_BY) {
        this.SUSPENDED_BY = SUSPENDED_BY == null ? null : SUSPENDED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.SUSPENDED_DATE
     *
     * @return the value of OC_APP_CHNL.SUSPENDED_DATE
     */
    public Date getSUSPENDED_DATE() {
        return SUSPENDED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.SUSPENDED_DATE
     *
     * @param SUSPENDED_DATE the value for OC_APP_CHNL.SUSPENDED_DATE
     */
    public void setSUSPENDED_DATE(Date SUSPENDED_DATE) {
        this.SUSPENDED_DATE = SUSPENDED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.REACTIVATED_BY
     *
     * @return the value of OC_APP_CHNL.REACTIVATED_BY
     */
    public String getREACTIVATED_BY() {
        return REACTIVATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.REACTIVATED_BY
     *
     * @param REACTIVATED_BY the value for OC_APP_CHNL.REACTIVATED_BY
     */
    public void setREACTIVATED_BY(String REACTIVATED_BY) {
        this.REACTIVATED_BY = REACTIVATED_BY == null ? null : REACTIVATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.REACTIVATED_DATE
     *
     * @return the value of OC_APP_CHNL.REACTIVATED_DATE
     */
    public Date getREACTIVATED_DATE() {
        return REACTIVATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.REACTIVATED_DATE
     *
     * @param REACTIVATED_DATE the value for OC_APP_CHNL.REACTIVATED_DATE
     */
    public void setREACTIVATED_DATE(Date REACTIVATED_DATE) {
        this.REACTIVATED_DATE = REACTIVATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.SUSPENDED_FROM_DATE
     *
     * @return the value of OC_APP_CHNL.SUSPENDED_FROM_DATE
     */
    public Date getSUSPENDED_FROM_DATE() {
        return SUSPENDED_FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.SUSPENDED_FROM_DATE
     *
     * @param SUSPENDED_FROM_DATE the value for OC_APP_CHNL.SUSPENDED_FROM_DATE
     */
    public void setSUSPENDED_FROM_DATE(Date SUSPENDED_FROM_DATE) {
        this.SUSPENDED_FROM_DATE = SUSPENDED_FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.SUSPENDED_TO_DATE
     *
     * @return the value of OC_APP_CHNL.SUSPENDED_TO_DATE
     */
    public Date getSUSPENDED_TO_DATE() {
        return SUSPENDED_TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.SUSPENDED_TO_DATE
     *
     * @param SUSPENDED_TO_DATE the value for OC_APP_CHNL.SUSPENDED_TO_DATE
     */
    public void setSUSPENDED_TO_DATE(Date SUSPENDED_TO_DATE) {
        this.SUSPENDED_TO_DATE = SUSPENDED_TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OC_APP_CHNL.SHOW_SUSPEND_REASON_LOGIN_YN
     *
     * @return the value of OC_APP_CHNL.SHOW_SUSPEND_REASON_LOGIN_YN
     */
    public String getSHOW_SUSPEND_REASON_LOGIN_YN() {
        return SHOW_SUSPEND_REASON_LOGIN_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OC_APP_CHNL.SHOW_SUSPEND_REASON_LOGIN_YN
     *
     * @param SHOW_SUSPEND_REASON_LOGIN_YN the value for OC_APP_CHNL.SHOW_SUSPEND_REASON_LOGIN_YN
     */
    public void setSHOW_SUSPEND_REASON_LOGIN_YN(String SHOW_SUSPEND_REASON_LOGIN_YN) {
        this.SHOW_SUSPEND_REASON_LOGIN_YN = SHOW_SUSPEND_REASON_LOGIN_YN == null ? null : SHOW_SUSPEND_REASON_LOGIN_YN.trim();
    }
}